version: '3.9'
services:
  app:
    build:
      context: .
    image: onkar21/mhba-app
    ports:
      - "8080:8081"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=sprint
      - SPRING_DATASOURCE_PASSWORD=team6
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=sprint
      - POSTGRES_PASSWORD=team6
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sprint"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db_data: {}